### ISSUE TITLE
Issue with shader for openGL and Unity

### ISSUE THREAD

**Issue by mmspacediagonal** [keijiro/Cloner#2]
Hello, Keijiro.
I have a problem with matte shader in opengl.
I worked with matte shader before in Unity with .shader file format.
In OpenGL the shader type is normally .glsl and not sure how can I implement matte shader into .glsl format. I am newbie in shader scripting.
I think you are super expert in shader scripting and I kindly hope you help me.
Thank you.
Makuna

**Comment by keijiro** [comment]
The topic seems to be irrelevant to this repository.

I'm closing this ticket. Feel free to reopen it if it's actually relevant.
