### ISSUE TITLE
There is option for personal meshes

### ISSUE THREAD

**Issue by masterchop** [keijiro/Cloner#3]
hi, i was pretty exited when i saw this but it only work with 1 specfic mesh. Is it possible to apply interactive point clouds, like the dancing one.

**Comment by keijiro** [comment]
I'd recommend using Skinner for using this kind of special effects with skinned mesh objects.

https://github.com/keijiro/Skinner

**Comment by masterchop** [comment]
Thanks, but converted meshes are not compatible between each other and only skinner reacts.
For example:
![jul 14 2017 6-54 am - edited](https://user-images.githubusercontent.com/8175824/28201766-087b6194-6862-11e7-81e9-902e1b10d946.gif)

**Comment by keijiro** [comment]
That's because Cloner doesn't support skinned meshes. There is no plan for adding skinning support.
