### ISSUE TITLE
Not running on osx

### ISSUE THREAD

**Issue by preamptive** [keijiro/Cloner#4]
I cant seem to get this running on my Mac Book Pro. Sould it run on osx?

**Comment by keijiro** [comment]
It must work with Metal on macOS. Could you verify it? (change the graphics API to Metal, or enable Metal Editor Support)

https://forum.unity3d.com/threads/metal-editor.450548/

**Comment by preamptive** [comment]
Yes that was the first thing I tried. I tried both Metal and OpenGL. I dont get any errors when running but the Game view just turns pink. (so i guessed material or shader error)
When I select the material I get the error...(Metal: GrabIntoRenderTexture mismatched grab pass: 81 / 115)

**Comment by preamptive** [comment]
another error I get when selecting the Gradient Spike (CosineGradient)...
Metal: Error creating pipeline state (Hidden/Klak/Chromatics/CosineGradient/Preview): Link failed: The type of fragment input user(TEXCOORD0) does not match the type of the corresponding vertex shader output
(null)

**Comment by keijiro** [comment]
Okay. Thanks for the info. By the way, which version of Unity/macOS are you using? I'll try to reproduce the issue.

**Comment by preamptive** [comment]
macOS 10.12.6
Unity 5.6.1f1
Thank you. If you need any more info just let me know as I would love to get this running! It looks impressive!

**Comment by jonathanhart** [comment]
I'm running into major issues too... MacOS 10.12.6 and Unity 2017.1.0f3...

I have enabled both Metal Editor support and API validation, and while it runs I see three things of note:

1) The Assets/Test folder has some pink assets like so:
![screen shot 2017-08-07 at 11 45 10 pm](https://user-images.githubusercontent.com/2595665/29059533-dd78a232-7bca-11e7-8952-a18cc1bae138.png)

2) The background begins to fill with what looks to be a mesh utilizing the assets from #1:
![screen shot 2017-08-07 at 11 25 27 pm](https://user-images.githubusercontent.com/2595665/29059547-ed590a84-7bca-11e7-8802-517e327927d8.png)

3) The framerate is well below 1fps and appears to get worse and worse until I have to reboot my computer. 

I have a late 2013 Macbook Pro so I assume I just am underpowered, but my datapoints may help in disclaimers for other potential coders.

**Comment by keijiro** [comment]
Fixed the issue in https://github.com/keijiro/Cloner/commit/1120493ca2df265d450de3ec1b38a1d388468964

I'm closing this issue. Please feel free to reopen if you find further problems.
