### ISSUE TITLE
Convert to Point cloud

### ISSUE THREAD

**Issue by CJHFUTURE** [keijiro/Cloner#5]
Hi,
Just wondering what is the workflow for using my own model as a cloner point cloud?
I see under/Assets/Cloner/convert to point cloud is greyed out

Thanks in advance:)
This plugin rules by the way:)

**Comment by keijiro** [comment]
You have to select a mesh inside a fbx file. See the attached screenshot.

![conversion](https://user-images.githubusercontent.com/343936/29052663-7176ed26-7c26-11e7-875c-8854accd3b32.png)

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen if it doesn't work for you.
