### ISSUE TITLE
Test works but not in a new project UnityException.FindKernel failed

### ISSUE THREAD

**Issue by mmos-studio** [keijiro/Cloner#6]
Hello keijiro thanks a lot for everything. I really like this, but i would like to use within my own project. The test you supplied works but when i try to use it in my own project it fails. 
Im using a mac. any ideas?

Thanks a lot! your work is amazing!

**Comment by keijiro** [comment]
It must work with Metal on macOS. Could you verify it? (change the graphics API to Metal, or enable Metal Editor Support)

https://forum.unity3d.com/threads/metal-editor.450548/

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen if you have further problems.
